### ISSUE TITLE
error running seq2HLA on mRNAseq 

### ISSUE THREAD

**Issue by katahdin0** [TRON-Bioinformatics/seq2HLA#18]
The error below seems to be arising from some software version incompatibility ? but it is not clear what. bowtie log is not empty, and bowtie version is 1.3.1

The digital haplotype is written into run-ClassI-class.digitalhaplotype2
Took 0.26239871978759766 seconds
2nd iteration done.
-----------2 digit typing results-------------
#Locus  Allele 1        Confidence      Allele 2        Confidence
A       no      NA      hoz("A*01")     NA
B       no      NA      hoz("B*07")     NA
C       no      NA      hoz("C*01")     NA
Calculation of locus-specific expression ...
run-ClassI-class.bowtielog
Traceback (most recent call last):
  File "/mnt/data/software/seq2HLA/seq2HLA.py", line 791, in <module>
    main()
  File "/mnt/data/software/seq2HLA/seq2HLA.py", line 786, in main
    pipe.run()
  File "/mnt/data/software/seq2HLA/seq2HLA.py", line 140, in run
    self.call_HLA(
  File "/mnt/data/software/seq2HLA/seq2HLA.py", line 252, in call_HLA
    self.expression(locus_list, length_dict, map, run_name)
  File "/mnt/data/software/seq2HLA/seq2HLA.py", line 694, in expression
    totalreads = float(linecache.getline(logfile, 1).split(':')[1])
IndexError: list index out of range
bash: 002/hla_map/tempus/R_2.fastq: No such file or directory

**Comment by katahdin0** [comment]
I installed the version of bowtie used to develop seq2HLA, so it seems to have moved past this error, but now fails at another step, with an equally opaque error, basically this never gets to the class II genotypes, only class I gets some stuff , I reverted to old version of bowtie and seq2HLA still fails after a while with this message , is this about python 2 versus python 3 ? The digital haplotype is written into /mnt/data/pfo/PFO002/hla_map/tempus/seq2HLA-ClassI-nonclass.digitalhaplotype3
Took 0.5703256130218506 seconds
Traceback (most recent call last):
  File "/mnt/data/software/seq2HLA/seq2HLA.py", line 791, in <module>
    main()
  File "/mnt/data/software/seq2HLA/seq2HLA.py", line 786, in main
    pipe.run()
  File "/mnt/data/software/seq2HLA/seq2HLA.py", line 152, in run
    self.call_HLA(
  File "/mnt/data/software/seq2HLA/seq2HLA.py", line 304, in call_HLA
    if fourDigit_solutions1[locus] > 1:
TypeError: '>' not supported between instances of 'str' and 'int'

**Comment by katahdin0** [comment]
Installing the old version of bowtie (0.12.7) and using python 2.7 fixed most problems, but one problem appeared in one dataset and that was due to a mistake in line 306 of seq2HLA,  the call to get_max_P should be replaced with self.get_max_P  and now there have been no more errors

**Comment by katahdin0** [comment]
so old version of bowtie (0.12.7), and python 2.7 with the appropriate biopython (pip install biopython==1.76) 
and a modification in seq2HLA   (line 306 replace get_max_P with self.get_maxP)   and the problems disappeared, at least for me
